### ISSUE TITLE
Deprecated exercises appear in todo list

### ISSUE THREAD

**Issue by bcc32** [exercism/ocaml#208]
Output of `exercism fetch`:

```
ocaml (Point Mutations)    [...]/exercism/ocaml/point-mutations
```

I imagine this has to do with 6bb1d9f, but I don't know enough about the CLI and `config.json` to offer any ideas.

**Comment by stevejb71** [comment]
@kytrinyx is this intended?

**Comment by kytrinyx** [comment]
Ah! No, that is a bug. I will fix it tonight. Thanks!

**Comment by kytrinyx** [comment]
OK, I've deployed a fix.

**Comment by stevejb71** [comment]
Tried it locally and I didn't get any deprecated exercises downloaded.

@bcc32 - if you're able to give it a try to test please do.

**Comment by bcc32** [comment]
Looks good on my end too. Thanks @stevejb71 @kytrinyx.

**Comment by kytrinyx** [comment]
Excellent, thanks for following up! 🌷
