### ISSUE TITLE
Allow ReasonML syntax

### ISSUE THREAD

**Issue by rdavison** [exercism/ocaml#230]
ReasonML is an up-and-coming dialect of OCaml.  I think we could encourage more people to try the language out if it was available on exercism.  I feel it should be relatively simple to add since ReasonML _is_ OCaml and we can reuse all the exercises available in the OCaml track.

**Comment by dvberkel** [comment]
Hi @rdavison,
Thanks for your suggestion to start using [ReasonML](https://reasonml.github.io/). I am not familiar with it. I will take some time to familiarize myself with it.

In the mean time. What is your expectation? Would ReasonML be a different language track on excercism?

**Comment by stevejb71** [comment]
I think this is a good idea. I think a separate stream might be better: ReasonML users might not understand or even be interested in OCaml, and v.v. All the exercises & tests would have to be re-written as well (even if with help from an automatic translator).

**Comment by stevejb71** [comment]
Closing, reasonml language track has started.
