### ISSUE TITLE
Failure in prime factors exercise on CI

### ISSUE THREAD

**Issue by kytrinyx** [exercism/ocaml#232]
The Travis CI build fails with the following error:

```
----------------------------------------------------------------
running tests for: prime-factors
+ ocamlfind ocamlopt -linkpkg -g -thread -package oUnit -package core prime_factors.cmx test.cmx -o test.native
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Big_int referenced from prime_factors.cmx
Command exited with code 2.
make[2]: *** [test.native] Error 10
make[1]: *** [test-assignment] Error 2
make: *** [test] Error 1
```

**Comment by stevejb71** [comment]
That's interesting, I don't recall the Travis build failing in my last commit (not since 4.06.0 upgrade).
Do you get the same results running the Makefile at the root of the source tree?
I can also take a look after my Christmas break.

**Comment by kytrinyx** [comment]
I've not installed an OCaml development environment—I don't think there's any hurry. After the Christmas break would be totally fine. Thanks!

**Comment by stevejb71** [comment]
Closed by https://github.com/exercism/ocaml/pull/238
