### ISSUE TITLE
Convert exercise dependencies from core_kernel to base

### ISSUE THREAD

**Issue by sshine** [exercism/ocaml#277]
Affected exercises:

- [`meetup`](https://github.com/exercism/ocaml/tree/master/exercises/meetup) uses `Date` from Core_kernel and can't simply be downgraded, I think.
- [x] [`zipper`](https://github.com/exercism/ocaml/tree/master/exercises/zipper) uses nothing outside Base and can trivially be downgraded.
- [x] [`word-count`](https://github.com/exercism/ocaml/tree/master/exercises/word-count) uses `String.Map` from Core_kernel and can somewhat simply be downgraded.
- [x] [`nucleotide-count`](https://github.com/exercism/ocaml/tree/master/exercises/nucleotide-count) uses `Char.Map` from Core_kernel and can somewhat simply be downgraded.
- [x] [`react`](https://github.com/exercism/ocaml/tree/master/exercises/react) uses the deprecated `succ` instead of `Int.succ` and `Int.Table` (which looks like a specialized `Hashtbl`) can be downgraded with a bit of fiddling.

The remaining 40 exercises all depend on Base.

**Comment by stevejb71** [comment]
Meetup could define its own date type.

**Comment by sshine** [comment]
Then the exercise would have to contain a function that converts a date to a weekday. I don't know if that's hard, but it's something I would like to expect is solved by a date library.

I would prefer if the exercise encouraged the use of existing popular libraries when ones exist.

I think this exercise belongs to Core_kernel unless there's another date module that is also popular.

**Comment by sshine** [comment]
I'll leave `meetup` as-is until a proposal to change it is made.
