### ISSUE TITLE
Inconsistency between README and tests for "connect"

### ISSUE THREAD

**Issue by emengd** [exercism/ocaml#302]
The README for the "connect" exercise states:
>The boards look like this (with spaces added for readability, which won't be in
the representation passed to your code):
```text
. O . X .
 . X X O .
  O O O X .
   . X O X O
    X O O O X
```

Based on this, I expected the same input to be formatted like this:
```text
.O.X.
.XXO.
OOOX.
.XOXO
XOOOX
```
(so a list of strings of equal length containing only `'X'`, `'O'` or `'.'`)

But actually, the test input is formatted like in the README (a list of strings of increasing lengths with a bunch of spaces).

The fix to make my code pass the tests was minimal (just ignore the spaces) but it would be better to be consistent.

EDIT : it looks like the issue is already in the canonical data (at some point the input was changed but the README wasn't updated).

EDIT 2: upstream issue: https://github.com/exercism/problem-specifications/issues/1435 and PR: https://github.com/exercism/problem-specifications/pull/1513

**Comment by sshine** [comment]
Thanks for pointing this out. I look forward to seeing the upstream issues resolved.

**Comment by sshine** [comment]
It seems that exercism/problem-specifications#1513 resolves this issue by removing the comment "with spaces added for readability, which won't be in the representation passed to your code", so now the task is to also remove this comment from exercises/connect/README.md.
