### ISSUE TITLE
oUnit is considered on transition to ounit2

### ISSUE THREAD

**Issue by MiyamotoAkira** [exercism/ocaml#442]
From the docs I see that you say to install `ounit`. OUnit2 seems to recommend now to use `ounit2` for the install, and also use `ounit2` rather than `oUnit` on the dune file (as per [OUnit github](https://github.com/gildor478/ounit#transition-to-ounit2))

A related issue seems to be:
https://github.com/exercism/ocaml/issues/364

**Comment by tautologico** [comment]
I think this was solved by [this PR](https://github.com/exercism/ocaml-test-runner/pull/33).

**Comment by MiyamotoAkira** [comment]
Indeed. Closing
