### ISSUE TITLE
Show the mli in the browser editor

### ISSUE THREAD

**Issue by tautologico** [exercism/ocaml#455]
I have noticed that in many problems, it's hard to understand what the required functions should do. You can read the tests, but when downloading exercises to my machine it's much faster to just look at the module interface in the mli file (and then read the tests). Many mli files also include documentation comments for the functions, which are not present in the ml file. 

I've seen in some other track that the web editor can show more than one file. I think showing the mli would be a great help to people who solve the problems using the browser editor.

**Comment by georgyo** [comment]
Looking at recently closed issues by the bot, this was solved in #462
