### ISSUE TITLE
Hamming tests are not consistent

### ISSUE THREAD

**Issue by Pamplemousse** [exercism/ocaml#467]
There is a test that checks that two empty strands should return `Ok 0`:
https://github.com/exercism/ocaml/blob/main/exercises/practice/hamming/test.ml#L24-L25

But also two checks that says "disallow * empty strand", expecting an error when given one of the two strands empty:
https://github.com/exercism/ocaml/blob/main/exercises/practice/hamming/test.ml#L38-L41

**Comment by georgyo** [comment]
@Pamplemousse You likely want to re-raise this on the forms, but this is not a specific to the ocaml tests. The problem-specifications repo dictates these tests.

https://github.com/exercism/problem-specifications/blob/main/exercises/hamming/canonical-data.json

https://github.com/exercism/problem-specifications/blob/0b1dfc291099273d56ef77ca71bf7ca8a502b352/exercises/hamming/canonical-data.json#L14-L21

https://github.com/exercism/problem-specifications/blob/0b1dfc291099273d56ef77ca71bf7ca8a502b352/exercises/hamming/canonical-data.json#L116-L125


my guess is that if both inputs are empty than the correct answer is 0. But if only a single input is empty than it is a mistake to error on.
