### ISSUE TITLE
Meetup: The stub is a complete solution

### ISSUE THREAD

**Issue by Lattay** [exercism/ocaml#491]
Hi,

The stub provided in meetup is a complete solution that passes all test.
Is this normal??

**Comment by georgyo** [comment]
Sorry for the auto-close, the removal of the pause on community contributions is still waiting review.

It seems like this was broken in this commit: https://github.com/exercism/ocaml/commit/02b80e77256e6433dc2461951cb72b057779d049

Feel free to send a PR either reverting that or fixing the the current stub. I'll be able to review and merge those contributions.

**Comment by Lattay** [comment]
Hi,
No worries, I went on and signaled the problem [on the forum](https://forum.exercism.org/t/ocaml-meetup-the-stub-is-a-complete-solution/8069).
I guess the fix is fairly easy, just remove anything that is not strictly required to guide the student.
I don't mind making such a PR if you are willing to merge it.

**Comment by georgyo** [comment]
Happy to merge it if you create the PR
