### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by iHiD** [exercism/ocaml#530]
@kahgoh You have qualified to be a maintainer here. Thank you for your hard work! Would you like to join?

**Comment by kahgoh** [comment]
@iHiD yes, I'd like to join

**Comment by ErikSchierboom** [comment]
Awesome. Thank you!

You've been added to the team. You have access to the #maintainers channel on Discord if your Exercism and Discord accounts [are linked](https://exercism.org/settings/integrations).

You can learn more about being a maintainer [here](https://exercism.org/docs/community/maintainers)

Thanks so much for your work, and welcome to the team :)
