### ISSUE TITLE
Add OCaml specific exercises

### ISSUE THREAD

**Issue by stevejb71** [exercism/ocaml#73]
It might be good to add some exercises that encourage exploration of features or common libraries that are special to OCaml. The existing base of exercises might not allow us to cover these, so we might have to make up new ones.

A few examples:
- The object system - it's deprecated by some, but still used in some libraries and in the compiler, and it is not uninteresting.
- First class modules
- js_of_ocaml - an Ocaml to Javascript compiler

**Comment by dvberkel** [comment]
I think this is a great idea! I was thinking of first class modules, because it is something I haven't seen in other languages I know.

**Comment by tmcgilchrist** [comment]
I think all of those would be interesting, plus something around just using the plain module system in OCaml. 

I don't think the object system is deprecated as much as there are other ways to achieve the same outcome. For an interesting, easily understandable example of using objects look at [ocaml-webmachine](https://github.com/inhabitedtype/ocaml-webmachine/).

**Comment by dvberkel** [comment]
I recently took interest in the integrated support for OCaml to define and use lexers and parsers. I will try to create an exercise around this concept.
